[selene]
base = "roblox"
name = "testez"

[[afterAll.args]]
required = true
type = "function"

[[afterEach.args]]
required = true
type = "function"

[[beforeAll.args]]
required = true
type = "function"

[[beforeEach.args]]
required = true
type = "function"

[[describe.args]]
required = true
type = "string"

[[describe.args]]
required = true
type = "function"

[[it.args]]
required = true
type = "string"

[[it.args]]
required = true
type = "function"

[[expect.args]]
required = true
type = "any"

[[expect.extend.args]]
required = true
type = "any"

[[fail.args]]
required = true
type = "string"

[[SKIP.args]]
required = false
type = "any"

[[FIXME.args]]
required = false
type = "any"

[[itSKIP.args]]
required = true
type = "string"


[[itSKIP.args]]
required = true
type = "function"


[[itFIXME.args]]
required = true
type = "string"

[[itFIXME.args]]
required = true
type = "function"
